export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
export const ACTION_SUCCESS = "ACTION_SUCCESS";
export const SET_MESSAGE = "SET_MESSAGE";

// Temp
export const SET_REGISTRATION_PREFERENCES = "SET_REGISTRATION_PREFERENCES";
